name: Question
description: Ask a question about the project
title: '[Question]: '
labels: ['question']
body:
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What do you want to know?
    validations:
      required: true

  - type: checkboxes
    id: consent
    attributes:
      label: Consent
      options:
        - label: I agree to follow this project's contributing guidelines
          required: true